<!--
ECMA-262 第 3 版引入了 try-catch 语句，作为 JavaScript 中处理异常的一种标准方式。
基本的语法如与 Java 中的 try-catch 语句是完全相同的。
-->
<!DOCTYPE html>
<html>
    <meta http-equiv="Content-Type" charset="utf-8" >
	<head>
        <script>
            /**
             应该把所有可能会抛出错误的代码都放在 try 语句块中，而把那些用于错误处理的代码放在 catch 块中。

             如果 try 块中的任何代码发生了错误，就会立即退出代码执行过程，然后接着执行 catch 块。
             此时，catch 块会接收到一个包含错误信息的对象。即使不想使用这个错误对象，也要给它起个名字。
             这个对象中包含的实际信息会因浏览器而异，但共同的是有一个保存着错误消息的 message 属性。

             虽然在 try-catch 语句中是可选的，但 finally 子句一经使用，其代码无论如何都会执行。
             换句话说，try 语句块中的代码全部正常执行，finally 子句会执行；
             如果因为出错而执行了 catch 语句块，finally 子句照样还会执行。
             只要代码中包含 finally 子句，则无论 try 或 catch 语句块中包含什么代码
             ——甚至 return 语句，都不会阻止 finally 子句的执行。
             */
            function showMessage() {
                try {
                    adddlert("Welcome guest!");// 故意写错 alert
                } catch (err) {
                    var txt = "本页有一个错误。\n\n";
                    txt += "错误描述：" + err.message + "\n\n";
                    txt += "点击确定继续。\n\n";
                    alert(txt);
                } finally {
                    alert("finally");
                }
            }
        </script>
	</head>
	<body>
		<input type="button" value="查看消息" onclick="showMessage()" />
	</body>

</html>
